export const countries = [
 {
   name: "Perú",
   country_code: "PE",
   phone_code: "+51",
   capital: "Lima",
 },
 {
   name: "Argentina",
   country_code: "AR",
   phone_code: "+54",
   capital: "Buenos Aires",
 },
 {
   name: "Bolivia",
   country_code: "BO",
   phone_code: "+591",
   capital: "Sucre",
 },
 {
   name: "Chile",
   country_code: "CL",
   phone_code: "+56",
   capital: "Santiago",
 },
 {
   name: "Colombia",
   country_code: "CO",
   phone_code: "+57",
   capital: "Bogotá",
 },
 {
   name: "Costa Rica",
   country_code: "CR",
   phone_code: "+506",
   capital: "San José",
 },
 {
   name: "Cuba",
   country_code: "CU",
   phone_code: "+53",
   capital: "La Habana",
 },
 {
   name: "Ecuador",
   country_code: "EC",
   phone_code: "+593",
   capital: "Quito",
 },
 {
   name: "El Salvador",
   country_code: "SV",
   phone_code: "+503",
   capital: "San Salvador",
 },
 {
   name: "Guatemala",
   country_code: "GT",
   phone_code: "+502",
   capital: "Ciudad de Guatemala",
 },
 {
   name: "Honduras",
   country_code: "HN",
   phone_code: "+504",
   capital: "Tegucigalpa",
 },
 {
   name: "México",
   country_code: "MX",
   phone_code: "+52",
   capital: "Ciudad de México",
 },
 {
   name: "Nicaragua",
   country_code: "NI",
   phone_code: "+505",
   capital: "Managua",
 },
 {
   name: "Panamá",
   country_code: "PA",
   phone_code: "+507",
   capital: "Ciudad de Panamá",
 },
 {
   name: "Paraguay",
   country_code: "PY",
   phone_code: "+595",
   capital: "Asunción",
 },
 {
   name: "República Dominicana",
   country_code: "DO",
   phone_code: "+1-809",
   capital: "Santo Domingo",
 },
 {
   name: "Uruguay",
   country_code: "UY",
   phone_code: "+598",
   capital: "Montevideo",
 },
 {
   name: "Venezuela",
   country_code: "VE",
   phone_code: "+58",
   capital: "Caracas",
 },
 {
   name: "España",
   country_code: "ES",
   phone_code: "+34",
   capital: "Madrid",
 },
];
